<%@ Page Language="VB" AutoEventWireup="false" CodeFile="ExportRepository.aspx.vb" Inherits="Meanstream_Host_UserControls_ExportRepository" %>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server" >


	<asp:GridView ID="ExportGrid" 
                            runat="server" 
                            AutoGenerateColumns="false" 
                            AutoGenerateEditButton="false" 
                            AutoGenerateDeleteButton="false">
                        </asp:GridView>


    </form>
</body>
</html>